Repository WgtTelia/Telia-e-shop-front-end, pull requests merged in 2024-08, with the labels that each got.

#2 UI folder structure and custom colors (TES-38 and TES-42)
  __test__/Home.test.jsx
  __test__/snapshot.js
  app/page.tsx
  package-lock.json
  package.json
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/TestButton.tsx
  tailwind.config.ts
Labels: setup

#3 fix: formatting
  README.md
Labels: documentation

#5 TES-30, TES-31, TES-32: global types, mock data, product card
  .eslintrc.json
  package-lock.json
  package.json
  public/images/apple_iPhone_15.png
  public/images/apple_iPhone_15_blue.png
  public/images/apple_iPhone_15_green.png
  public/images/apple_iPhone_15_pink.png
  public/images/apple_iPhone_15_yellow.png
  public/images/onePlus_Nord_3_gray.png
  public/images/onePlus_Nord_3_green.png
  public/images/samsung_Galaxy_S23_FE.png
  public/images/samsung_Galaxy_S23_FE_gray.png
  public/images/samsung_Galaxy_S23_FE_lavender.png
  public/images/samsung_Galaxy_S23_FE_white.png
  public/images/sony_Xperia_10_V_black.png
  public/images/sony_Xperia_10_V_green.png
  public/images/sony_Xperia_10_V_white.png
  public/images/xiaomi_Redmi_Note_13_blue.png
  public/images/xiaomi_Redmi_Note_13_white.png
  src/app/__tests__/Page.test.jsx
  src/app/globals.css
  src/app/page.tsx
  src/components/ButtonCTA.test.jsx
  src/components/ButtonCTA.tsx
  src/components/ColorDots.jsx
  src/components/ColorDots.tsx
  src/components/ProductCard.test.jsx
  src/components/ProductCard.tsx
  src/components/ProductGrid.test.jsx
  src/components/ProductGrid.tsx
  src/components/StockStatus.tsx
  src/components/TestButton.tsx
  src/data/mockData.js
  src/data/products.json
  src/types/global.d.ts
  src/utils/colorUtils.test.js
  src/utils/colorUtils.ts
  tailwind.config.ts
Labels: enhancement, setup

#8 Tes 40 install shadcn UI
  .eslintrc.json
  components.json
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/ColorDots.test.jsx
  src/components/ColorDots.tsx
  src/components/OrderNowBtn.test.tsx
  src/components/OrderNowBtn.tsx
  src/components/ProductCard.test.tsx
  src/components/ProductGrid.test.tsx
  src/components/ui/button.tsx
  src/data/mockData.js
  src/lib/colorUtils.test.js
  src/lib/colorUtils.ts
  src/lib/utils.ts
  tailwind.config.ts
Labels: enhancement
